### ISSUE TITLE
BinEvalWeights

### ISSUE THREAD

**Issue by juvian** [kzagoris/DibcoEvaluation#1]
Hello, is there no code available for BinEvalWeights.exe ?

**Comment by kzagoris** [comment]
The DIBCO competitions are started many years ago. Therefore, they have very old implementations which we mostly keep intact for comparison between different competitions. 
The BinEvalWeights executable is used by one of a metric chosen in DIBCO. 

The executable generates two .dat files containing
the normalized distance weights for pseudo-Recall/Precision based on the paper:

K. Ntirogiannis, B. Gatos and I. Pratikakis
"Performance Evaluation Methodology for Historical Document Image Binarization"
IEEE Trans. Image Proc., vol.22, no.2, pp. 595-609, Feb. 2013.

The executable is provided by the authors of the above paper and it is the official implementation.

I do not have the source available (it is not my code after all). Probably,  you need to ask the above authors for the source implementation.
